const actionTypeConfig = {
    GET_BONUSES_LIST_ACTION: "GET_BONUSES_LIST_ACTION",
    GET_NEW_BONUSES_ACTION: "GET_NEW_BONUSES_ACTION",
    RESET_BONUSES_ACTION: "RESET_BONUSES_ACTION",
    CHANGE_NEW_BONUSES_ID_ACTION: "CHANGE_NEW_BONUSES_ID_ACTION"
};

export default actionTypeConfig;